version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: blog_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Реализованный сервис приложения app взамен TODO
  app:
    build: .
    container_name: blog_api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: db # Имя сервиса БД в локальной сети Docker Compose
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: blog_db
      DB_SSLMODE: disable
      JWT_SECRET: your-secret-key-change-in-production
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
    depends_on:
      db:
        condition: service_healthy # Приложение запустится только после успешного прохождения healthcheck базой данных

volumes:
  postgres_data:
